//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public string Id { get; set; }
        public string OrderId { get; set; }
        public System.DateTime Date { get; set; }
        public string StaffId { get; set; }
        public bool IsDelivered { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
