//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import
    {
        public Import()
        {
            this.ImportDetails = new HashSet<ImportDetail>();
        }
    
        public string Id { get; set; }
        public string PackageId { get; set; }
        public string SupplierId { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<ImportDetail> ImportDetails { get; set; }
    }
}
