
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProductPartial
{

    public string ProductID { get; set; }

    public string ScreenSize { get; set; }

    public string OS { get; set; }

    public string Camera1 { get; set; }

    public string Camera2 { get; set; }

    public string CPU { get; set; }

    public string Ram { get; set; }

    public string InterMemory { get; set; }

    public string Connection { get; set; }



    public virtual Product Product { get; set; }

}

}
