
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Promotion
{

    public Promotion()
    {

        this.Products = new HashSet<Product>();

    }


    public string Id { get; set; }

    public string Name { get; set; }

    public System.DateTime StartDate { get; set; }

    public System.DateTime EndDate { get; set; }

    public double SaleOff { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public bool Deleted { get; set; }



    public virtual ICollection<Product> Products { get; set; }

}

}
